# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineip', models.GenericIPAddressField(null=True)),
                ('dockerid', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('C', 'Creating'), ('R', 'Running'), ('D', 'Down'), ('F', 'Failed')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('maxmachine', models.IntegerField(default=1)),
                ('userpass', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui.User'),
        ),
    ]
