# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_auto_20160419_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clouduser',
            name='userpass',
        ),
    ]
