# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webui', '0003_remove_clouduser_userpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('machineip', models.GenericIPAddressField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
