# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='dockerid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
